const camposPublicacion = [
    { campo: 'orden', etiqueta: 'Orden', tipo: 'numero' },
    { campo: 'publicado', etiqueta: 'Publicado', tipo: 'booleano' },
];

export const recursosAdmin = {
    'configuracion-sitio': {
        titulo: 'Configuración del sitio',
        permiso: 'configuracion.editar',
        recurso: 'configuracion-sitio',
        columnas: ['nombre_sitio', 'anio_principal', 'correo_contacto'],
        campos: [
            { campo: 'nombre_sitio', etiqueta: 'Nombre del sitio' },
            { campo: 'subtitulo_sitio', etiqueta: 'Subtítulo' },
            { campo: 'anio_principal', etiqueta: 'Año principal', tipo: 'numero' },
            { campo: 'fecha_principal', etiqueta: 'Fecha principal' },
            { campo: 'titulo_portada', etiqueta: 'Título de portada' },
            { campo: 'subtitulo_portada', etiqueta: 'Subtítulo de portada', tipo: 'texto' },
            { campo: 'imagen_portada', etiqueta: 'Imagen de portada' },
            { campo: 'video_portada', etiqueta: 'Video de portada' },
            { campo: 'logo', etiqueta: 'Logo' },
            { campo: 'color_primario', etiqueta: 'Color primario' },
            { campo: 'color_secundario', etiqueta: 'Color secundario' },
            { campo: 'telefono_contacto', etiqueta: 'Teléfono' },
            { campo: 'correo_contacto', etiqueta: 'Correo' },
            { campo: 'url_facebook', etiqueta: 'Facebook' },
            { campo: 'url_youtube', etiqueta: 'YouTube' },
            { campo: 'url_tiktok', etiqueta: 'TikTok' },
            { campo: 'url_instagram', etiqueta: 'Instagram' },
        ],
    },
    historia: {
        titulo: 'Historia',
        permiso: 'historia.administrar',
        recurso: 'historia',
        columnas: ['titulo', 'orden', 'publicado'],
        campos: [
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'subtitulo', etiqueta: 'Subtítulo' },
            { campo: 'contenido', etiqueta: 'Contenido', tipo: 'texto' },
            { campo: 'imagen', etiqueta: 'Imagen' },
            ...camposPublicacion,
        ],
    },
    mayordomias: {
        titulo: 'Mayordomías',
        permiso: 'mayordomia.administrar',
        recurso: 'mayordomias',
        columnas: ['anio', 'titulo', 'actual', 'publicado'],
        campos: [
            { campo: 'anio', etiqueta: 'Año', tipo: 'numero' },
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'nombre_familia', etiqueta: 'Familia' },
            { campo: 'nombre_mayordoma_principal', etiqueta: 'Mayordoma principal' },
            { campo: 'mensaje', etiqueta: 'Mensaje', tipo: 'texto' },
            { campo: 'imagen', etiqueta: 'Imagen' },
            { campo: 'actual', etiqueta: 'Actual', tipo: 'booleano' },
            { campo: 'publicado', etiqueta: 'Publicado', tipo: 'booleano' },
        ],
    },
    'dias-programa': {
        titulo: 'Días del programa',
        permiso: 'programa.administrar',
        recurso: 'dias-programa',
        columnas: ['fecha', 'titulo', 'orden', 'publicado'],
        campos: [
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'descripcion', etiqueta: 'Descripción', tipo: 'texto' },
            { campo: 'fecha', etiqueta: 'Fecha' },
            ...camposPublicacion,
        ],
    },
    'actividades-programa': {
        titulo: 'Actividades del programa',
        permiso: 'programa.administrar',
        recurso: 'actividades-programa',
        columnas: ['dia_programa_id', 'titulo', 'hora_inicio', 'publicado'],
        campos: [
            { campo: 'dia_programa_id', etiqueta: 'Día programa ID', tipo: 'numero' },
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'descripcion', etiqueta: 'Descripción', tipo: 'texto' },
            { campo: 'hora_inicio', etiqueta: 'Hora inicio' },
            { campo: 'hora_fin', etiqueta: 'Hora fin' },
            { campo: 'nombre_lugar', etiqueta: 'Lugar' },
            { campo: 'direccion', etiqueta: 'Dirección' },
            { campo: 'url_mapa', etiqueta: 'URL mapa' },
            { campo: 'url_mapa_incrustado', etiqueta: 'Mapa embebido', tipo: 'texto' },
            { campo: 'responsable', etiqueta: 'Responsable' },
            ...camposPublicacion,
        ],
    },
    albumes: {
        titulo: 'Álbumes',
        permiso: 'galeria.administrar',
        recurso: 'albumes',
        columnas: ['titulo', 'slug', 'anio', 'publicado'],
        campos: [
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'slug', etiqueta: 'Slug' },
            { campo: 'descripcion', etiqueta: 'Descripción', tipo: 'texto' },
            { campo: 'anio', etiqueta: 'Año', tipo: 'numero' },
            { campo: 'foto_portada_id', etiqueta: 'Foto portada ID', tipo: 'numero' },
            ...camposPublicacion,
        ],
    },
    fotos: {
        titulo: 'Fotos',
        permiso: 'galeria.administrar',
        recurso: 'fotos',
        columnas: ['album_id', 'titulo', 'ruta_archivo', 'publicado'],
        campos: [
            { campo: 'album_id', etiqueta: 'Álbum ID', tipo: 'numero' },
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'descripcion', etiqueta: 'Descripción', tipo: 'texto' },
            { campo: 'ruta_archivo', etiqueta: 'Ruta archivo' },
            { campo: 'ruta_miniatura', etiqueta: 'Ruta miniatura' },
            { campo: 'ruta_mediana', etiqueta: 'Ruta mediana' },
            ...camposPublicacion,
        ],
    },
    videos: {
        titulo: 'Videos',
        permiso: 'videos.administrar',
        recurso: 'videos',
        columnas: ['titulo', 'slug', 'categoria', 'publicado'],
        campos: [
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'slug', etiqueta: 'Slug' },
            { campo: 'descripcion', etiqueta: 'Descripción', tipo: 'texto' },
            { campo: 'url_video', etiqueta: 'URL video' },
            { campo: 'url_incrustado', etiqueta: 'URL embebida', tipo: 'texto' },
            { campo: 'miniatura', etiqueta: 'Miniatura' },
            { campo: 'categoria', etiqueta: 'Categoría' },
            { campo: 'anio', etiqueta: 'Año', tipo: 'numero' },
            { campo: 'orden', etiqueta: 'Orden', tipo: 'numero' },
            { campo: 'destacado', etiqueta: 'Destacado', tipo: 'booleano' },
            { campo: 'publicado', etiqueta: 'Publicado', tipo: 'booleano' },
        ],
    },
    comunicados: {
        titulo: 'Comunicados',
        permiso: 'comunicados.administrar',
        recurso: 'comunicados',
        columnas: ['titulo', 'slug', 'destacado', 'publicado'],
        campos: [
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'slug', etiqueta: 'Slug' },
            { campo: 'contenido', etiqueta: 'Contenido', tipo: 'texto' },
            { campo: 'imagen', etiqueta: 'Imagen' },
            { campo: 'destacado', etiqueta: 'Destacado', tipo: 'booleano' },
            { campo: 'publicado', etiqueta: 'Publicado', tipo: 'booleano' },
            { campo: 'publicado_en', etiqueta: 'Publicado en' },
        ],
    },
    ubicaciones: {
        titulo: 'Ubicaciones',
        permiso: 'ubicaciones.administrar',
        recurso: 'ubicaciones',
        columnas: ['titulo', 'tipo', 'orden', 'publicado'],
        campos: [
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'descripcion', etiqueta: 'Descripción', tipo: 'texto' },
            { campo: 'direccion', etiqueta: 'Dirección' },
            { campo: 'url_mapa', etiqueta: 'URL mapa' },
            { campo: 'url_mapa_incrustado', etiqueta: 'Mapa embebido', tipo: 'texto' },
            { campo: 'tipo', etiqueta: 'Tipo' },
            ...camposPublicacion,
        ],
    },
    colaboradores: {
        titulo: 'Colaboradores',
        permiso: 'colaboradores.administrar',
        recurso: 'colaboradores',
        columnas: ['nombre', 'tipo', 'orden', 'publicado'],
        campos: [
            { campo: 'nombre', etiqueta: 'Nombre' },
            { campo: 'descripcion', etiqueta: 'Descripción', tipo: 'texto' },
            { campo: 'tipo', etiqueta: 'Tipo' },
            { campo: 'imagen', etiqueta: 'Imagen' },
            ...camposPublicacion,
        ],
    },
    'archivo-historico': {
        titulo: 'Archivo histórico',
        permiso: 'archivo_historico.administrar',
        recurso: 'archivo-historico',
        columnas: ['anio', 'titulo', 'orden', 'publicado'],
        campos: [
            { campo: 'anio', etiqueta: 'Año', tipo: 'numero' },
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'descripcion', etiqueta: 'Descripción', tipo: 'texto' },
            { campo: 'mayordomos', etiqueta: 'Mayordomos', tipo: 'texto' },
            { campo: 'imagen_portada', etiqueta: 'Imagen portada' },
            ...camposPublicacion,
        ],
    },
    personas: {
        titulo: 'Personas',
        permiso: 'seguridad.personas.administrar',
        recurso: 'personas',
        columnas: ['nombres', 'apellido_paterno', 'apellido_materno', 'numero_documento', 'correo'],
        campos: [
            { campo: 'nombres', etiqueta: 'Nombres' },
            { campo: 'apellido_paterno', etiqueta: 'Apellido paterno' },
            { campo: 'apellido_materno', etiqueta: 'Apellido materno' },
            { campo: 'tipo_documento_id', etiqueta: 'Tipo documento ID', tipo: 'numero' },
            { campo: 'numero_documento', etiqueta: 'Número documento' },
            { campo: 'fecha_nacimiento', etiqueta: 'Fecha nacimiento' },
            { campo: 'sexo_id', etiqueta: 'Sexo ID', tipo: 'numero' },
            { campo: 'direccion', etiqueta: 'Dirección' },
            { campo: 'distrito_id', etiqueta: 'Distrito ID', tipo: 'numero' },
            { campo: 'referencia', etiqueta: 'Referencia', tipo: 'texto' },
            { campo: 'correo', etiqueta: 'Correo' },
            { campo: 'telefono_movil', etiqueta: 'Teléfono móvil' },
            { campo: 'foto_path', etiqueta: 'Foto' },
            { campo: 'estado_id', etiqueta: 'Estado ID', tipo: 'numero' },
        ],
    },
    'catalogos/sexos': {
        titulo: 'Sexos',
        permiso: 'catalogos.sexos.administrar',
        recurso: 'catalogos/sexos',
        columnas: ['nombre', 'estado_id'],
        campos: [
            { campo: 'nombre', etiqueta: 'Nombre' },
            { campo: 'estado_id', etiqueta: 'Estado ID', tipo: 'numero' },
        ],
    },
    'catalogos/tipos-documento-identidad': {
        titulo: 'Tipos de documento',
        permiso: 'catalogos.tipos_documento.administrar',
        recurso: 'catalogos/tipos-documento-identidad',
        columnas: ['nombre', 'abreviatura', 'caracteres_max', 'estado_id'],
        campos: [
            { campo: 'nombre', etiqueta: 'Nombre' },
            { campo: 'abreviatura', etiqueta: 'Abreviatura' },
            { campo: 'caracteres_max', etiqueta: 'Caracteres máximo', tipo: 'numero' },
            { campo: 'estado_id', etiqueta: 'Estado ID', tipo: 'numero' },
        ],
    },
    'catalogos/departamentos': {
        titulo: 'Departamentos',
        permiso: 'catalogos.departamentos.administrar',
        recurso: 'catalogos/departamentos',
        columnas: ['codigo', 'nombre', 'ubigeo_dni', 'ubigeo_inei', 'estado_id'],
        campos: [
            { campo: 'codigo', etiqueta: 'Código' },
            { campo: 'nombre', etiqueta: 'Nombre' },
            { campo: 'ubigeo_dni', etiqueta: 'Ubigeo DNI' },
            { campo: 'ubigeo_inei', etiqueta: 'Ubigeo INEI' },
            { campo: 'estado_id', etiqueta: 'Estado ID', tipo: 'numero' },
        ],
    },
    'catalogos/provincias': {
        titulo: 'Provincias',
        permiso: 'catalogos.provincias.administrar',
        recurso: 'catalogos/provincias',
        columnas: ['departamento_id', 'codigo', 'nombre', 'ubigeo_dni', 'ubigeo_inei', 'estado_id'],
        campos: [
            { campo: 'departamento_id', etiqueta: 'Departamento ID', tipo: 'numero' },
            { campo: 'codigo', etiqueta: 'Código' },
            { campo: 'nombre', etiqueta: 'Nombre' },
            { campo: 'ubigeo_dni', etiqueta: 'Ubigeo DNI' },
            { campo: 'ubigeo_inei', etiqueta: 'Ubigeo INEI' },
            { campo: 'estado_id', etiqueta: 'Estado ID', tipo: 'numero' },
        ],
    },
    'catalogos/distritos': {
        titulo: 'Distritos',
        permiso: 'catalogos.distritos.administrar',
        recurso: 'catalogos/distritos',
        columnas: ['provincia_id', 'codigo', 'nombre', 'capital', 'ubigeo_dni', 'ubigeo_inei', 'estado_id'],
        campos: [
            { campo: 'provincia_id', etiqueta: 'Provincia ID', tipo: 'numero' },
            { campo: 'codigo', etiqueta: 'Código' },
            { campo: 'nombre', etiqueta: 'Nombre' },
            { campo: 'capital', etiqueta: 'Capital' },
            { campo: 'ubigeo_dni', etiqueta: 'Ubigeo DNI' },
            { campo: 'ubigeo_inei', etiqueta: 'Ubigeo INEI' },
            { campo: 'estado_id', etiqueta: 'Estado ID', tipo: 'numero' },
        ],
    },
    'interfaz/menus': {
        titulo: 'Menús',
        permiso: 'interfaz.menus.administrar',
        recurso: 'interfaz/menus',
        columnas: ['titulo', 'icono', 'orden', 'estado_id'],
        campos: [
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'icono', etiqueta: 'Icono' },
            { campo: 'orden', etiqueta: 'Orden', tipo: 'numero' },
            { campo: 'estado_id', etiqueta: 'Estado ID', tipo: 'numero' },
        ],
    },
    'interfaz/menu-items': {
        titulo: 'Items de menú',
        permiso: 'interfaz.menu_items.administrar',
        recurso: 'interfaz/menu-items',
        columnas: ['menu_id', 'parent_id', 'tipo', 'titulo', 'ruta', 'permiso_codigo', 'orden'],
        campos: [
            { campo: 'menu_id', etiqueta: 'Menú ID', tipo: 'numero' },
            { campo: 'parent_id', etiqueta: 'Padre ID', tipo: 'numero' },
            { campo: 'tipo', etiqueta: 'Tipo' },
            { campo: 'titulo', etiqueta: 'Título' },
            { campo: 'icono', etiqueta: 'Icono' },
            { campo: 'ruta', etiqueta: 'Ruta' },
            { campo: 'permiso_codigo', etiqueta: 'Permiso código' },
            { campo: 'orden', etiqueta: 'Orden', tipo: 'numero' },
            { campo: 'estado_id', etiqueta: 'Estado ID', tipo: 'numero' },
        ],
    },
};

export const menuAdmin = [
    { etiqueta: 'Panel', ruta: '/admin/dashboard', icono: 'pi pi-home', permiso: 'dashboard.ver' },
    { etiqueta: 'Configuración', ruta: '/admin/configuracion-sitio', icono: 'pi pi-cog', permiso: 'configuracion.editar' },
    { etiqueta: 'Historia', ruta: '/admin/historia', icono: 'pi pi-book', permiso: 'historia.administrar' },
    { etiqueta: 'Mayordomías', ruta: '/admin/mayordomias', icono: 'pi pi-users', permiso: 'mayordomia.administrar' },
    { etiqueta: 'Programa', ruta: '/admin/dias-programa', icono: 'pi pi-calendar', permiso: 'programa.administrar' },
    { etiqueta: 'Actividades', ruta: '/admin/actividades-programa', icono: 'pi pi-clock', permiso: 'programa.administrar' },
    { etiqueta: 'Álbumes', ruta: '/admin/albumes', icono: 'pi pi-images', permiso: 'galeria.administrar' },
    { etiqueta: 'Fotos', ruta: '/admin/fotos', icono: 'pi pi-image', permiso: 'galeria.administrar' },
    { etiqueta: 'Videos', ruta: '/admin/videos', icono: 'pi pi-video', permiso: 'videos.administrar' },
    { etiqueta: 'Comunicados', ruta: '/admin/comunicados', icono: 'pi pi-megaphone', permiso: 'comunicados.administrar' },
    { etiqueta: 'Ubicaciones', ruta: '/admin/ubicaciones', icono: 'pi pi-map-marker', permiso: 'ubicaciones.administrar' },
    { etiqueta: 'Colaboradores', ruta: '/admin/colaboradores', icono: 'pi pi-heart', permiso: 'colaboradores.administrar' },
    { etiqueta: 'Archivo histórico', ruta: '/admin/archivo-historico', icono: 'pi pi-folder', permiso: 'archivo_historico.administrar' },
    { etiqueta: 'Seguridad', ruta: '/admin/seguridad', icono: 'pi pi-shield', permiso: 'seguridad.usuarios.administrar' },
];
